<?php


/**
 * Implements hook_menu().
 */
function pdf_downloader_menu() {
    $items = array();
    $items['islandora/pdfdloader/dload'] = array(
        'page callback' => 'pdf_downloader_dload_pdf',
        'access arguments' => array('access publication alert links'),
        'type' => MENU_CALLBACK,
    );
    
    return $items;
}



function pdf_downloader_dload_pdf($doi = NULL){
    if (!$doi){
        $doi = trim($_GET['DOI'],'_');
    }
    
    module_load_include('php', 'pdf_downloader', 'lib/pdf_downloader');
    
    $down = new PdfDownloader();   
    return($down->returnPdf($doi));    
}

